name:                relatively-good-language
version:             0.1.0.0
license:             MIT
author:              "My Name"
maintainer:          "my@address.here"
copyright:           "2022 Author name here"

extra-source-files:
- README.md

description:         Implementation of Relatively Good Language.

dependencies:
- base >= 4.7 && < 5
- parsec >= 3.1 && < 3.2
- sprockell >= 2022.0
- hspec >= 2.8 && < 2.9
- QuickCheck >= 2.14 && < 2.15

library:
  source-dirs: src

executables:
  relatively-good-language-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - relatively-good-language

tests:
  relatively-good-language-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - relatively-good-language
